import { defineConfig, globalIgnores } from 'eslint/config';
import tsParser from '@typescript-eslint/parser';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import globals from 'globals';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';
import { fileURLToPath } from 'url';
import path from 'path';

// 模拟 __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

// 将 compat.extends() 提取为独立的配置数组
const compatConfigs = compat.extends(
  'eslint:recommended',
  'plugin:@typescript-eslint/recommended',
);

export default defineConfig([
  // 1. 首先应用 compat 配置
  ...compatConfigs,

  // 2. TypeScript 主配置
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          legacyDecorators: true,
          module: true,
        },
        allowImportExportEverywhere: true,
        requireConfigFile: false,
        project: './tsconfig.app.json',
        tsconfigRootDir: __dirname,
        extraFileExtensions: ['.vue', '.svelte'],
        warnOnUnsupportedTypeScriptVersion: false,
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...Object.fromEntries(Object.entries(globals.jquery).map(([key]) => [key, 'off'])),
      },
    },
    plugins: { '@typescript-eslint': typescriptEslint },
    linterOptions: { reportUnusedDisableDirectives: 'warn' },
    rules: {
      'no-return-assign': 'warn',
      'no-useless-concat': 'warn',
      'no-eq-null': 'warn',
      'no-useless-call': 2,
      'no-else-return': 'warn',
      'array-callback-return': 'error',
      'no-self-compare': 'warn',
      'no-empty': 'warn',
      'no-sequences': 'error',
      'no-useless-computed-key': 'error',
      'no-constant-condition': 'error',
      'no-loss-of-precision': 'off',
      'space-infix-ops': 'error',
      'no-trailing-spaces': 'warn',
      quotes: ['warn', 'single'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-script-url': 'error',
      'no-extend-native': 'error',
      'no-proto': 'error',
      'no-new-func': 'error',
      'new-cap': 'warn',
      'id-length': ['warn', { max: 40, min: 1 }],
      camelcase: 'off',
      '@typescript-eslint/naming-convention': [
        'warn',
        {
          selector: 'default', format: ['camelCase'], leadingUnderscore: 'allow', trailingUnderscore: 'allow',
        },
        { selector: 'typeLike', format: ['PascalCase'] },
        { selector: 'variable', format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'import', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
        { selector: 'variable', modifiers: ['const'], format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'property', format: ['camelCase', 'PascalCase', 'UPPER_CASE'], leadingUnderscore: 'allow' },
        { selector: 'accessor', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
      ],
      'no-shadow-restricted-names': 'error',
      'no-magic-numbers': ['off', { ignoreArrayIndexes: true, ignore: [-1, 0, 1, 2, 3, 4, 5, 8] }],
      'multiline-comment-style': ['error', 'separate-lines'],
      'line-comment-position': ['warn', { position: 'above' }],
      'lines-around-comment': ['error', { beforeBlockComment: true, beforeLineComment: false, allowBlockStart: true }],
      'spaced-comment': ['error', 'always'],
      'no-warning-comments': ['off', { terms: ['TODO', 'FIXME', 'DTS'], location: 'anywhere' }],
      indent: ['warn', 2, { SwitchCase: 1 }],
      'max-len': ['warn', { code: 120, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true }],
      'brace-style': 'error',
      'keyword-spacing': ['error', { before: true }],
      'space-before-function-paren': ['off', 'always'],
      'no-multi-spaces': 'error',
      curly: 'error',
      'no-var': 'error',
      'one-var': ['error', 'never'],
      'no-multi-assign': 'warn',
      'no-undef-init': 'error',
      'no-undef': 'off',
      'no-new-object': 'error',
      'no-param-reassign': ['warn', { props: false }],
      'prefer-rest-params': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-parens': ['error', 'always'],
      'arrow-body-style': ['error', 'as-needed'],
      'consistent-return': 'warn',
      'no-this-before-super': 'error',
      'prefer-template': 'error',
      'prefer-destructuring': ['off', { array: true, object: true }],
      'dot-notation': 'warn',
      'accessor-pairs': 'warn',
      'no-prototype-builtins': 'error',
      'guard-for-in': 'warn',
      'no-nested-ternary': 'warn',
      'default-case': 'warn',
      'no-fallthrough': 'error',
      'no-case-declarations': 2,
      'no-duplicate-imports': 'warn',
      'no-floating-decimal': 'error',
      'use-isnan': 2,
      'no-unsafe-finally': 'error',
      'no-return-await': 'error',
      'no-with': 'error',
      'no-console': 'off',
      'no-alert': 'error',
      'no-debugger': 'error',
      'no-implicit-coercion': 'warn',
      'no-useless-return': 'error',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'warn',
      'function-paren-newline': ['warn', 'multiline'],
      'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
      'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 4 }],
      'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
      'padded-blocks': ['off', { classes: 'never' }],
      'no-multiple-empty-lines': ['warn', { max: 1 }],
      'object-curly-spacing': ['warn', 'always'],
      'array-bracket-spacing': ['warn', 'never'],
      'comma-dangle': ['warn', 'always-multiline'],
      semi: ['warn', 'always'],
      'comma-spacing': ['warn', { before: false, after: true }],
      'max-lines': ['warn', 2000],
      'max-lines-per-function': ['warn', { max: 100 }],
      complexity: ['warn', 30],
      'max-depth': ['warn', 5],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['warn', 5],
      'func-style': ['warn', 'expression', { allowArrowFunctions: true }],
      eqeqeq: 'warn',
      'no-unexpected-multiline': 'warn',
      'no-negated-condition': 'warn',
      'no-mixed-operators': ['warn', {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: true,
      }],
      'no-implicit-globals': 'warn',
      'no-throw-literal': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'no-continue': 'warn',
      'vars-on-top': 'warn',
      strict: ['warn', 'function'],
      'no-new': 'error',
      'no-useless-escape': 'warn',
      'prefer-const': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [1, { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
      'no-tabs': 'error',
      'no-empty-function': 'off',
      'no-duplicate-case': 2,
      'no-mixed-spaces-and-tabs': ['error'],
      'no-dupe-class-members': 'off',
      'eol-last': 'error',
      'object-curly-newline': ['warn', {
        ObjectExpression: { multiline: true, minProperties: 4 },
        ObjectPattern: { multiline: true, minProperties: 4 },
        ImportDeclaration: { multiline: true, minProperties: 4 },
        ExportDeclaration: { multiline: true, minProperties: 4 },
      }],
      'quote-props': ['error', 'as-needed'],
      'key-spacing': ['error'],
      'space-before-blocks': ['error'],
      'semi-spacing': ['error', { before: false, after: true }],
      'arrow-spacing': ['error'],
      'space-in-parens': ['error', 'never'],
      'no-use-before-define': 'off',
      '@typescript-eslint/no-use-before-define': ['warn'],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-interface': 'warn',
      'no-useless-assignment': 'warn',
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/prefer-for-of': 'warn',
      '@typescript-eslint/no-var-requires': 'error',
      'sort-imports': ['off', {
        ignoreCase: false,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
        allowSeparatedGroups: false,
      }],
      '@typescript-eslint/consistent-type-imports': ['warn', {
        prefer: 'type-imports',
        disallowTypeAnnotations: false,
      }],
      '@typescript-eslint/no-import-type-side-effects': 'warn',
      '@typescript-eslint/ban-ts-comment': ['warn', { 'ts-nocheck': true, 'ts-check': false, 'ts-expect-error': 'allow-with-description', 'ts-ignore': 'allow-with-description' }],
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
    },
  },

  // 3. JavaScript 文件配置
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...Object.fromEntries(Object.entries(globals.jquery).map(([key]) => [key, 'off'])),
      },
    },
    linterOptions: { reportUnusedDisableDirectives: 'warn' },
    rules: {
      'no-return-assign': 'warn',
      'no-useless-concat': 'warn',
      'no-eq-null': 'warn',
      'no-useless-call': 2,
      'no-else-return': 'warn',
      'array-callback-return': 'error',
      'no-self-compare': 'warn',
      'no-empty': 'warn',
      'no-sequences': 'error',
      'no-useless-computed-key': 'error',
      'no-constant-condition': 'error',
      'no-loss-of-precision': 'off',
      'space-infix-ops': 'error',
      'no-trailing-spaces': 'warn',
      quotes: ['warn', 'single'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-script-url': 'error',
      'no-extend-native': 'error',
      'no-proto': 'error',
      'no-new-func': 'error',
      'new-cap': 'warn',
      'id-length': ['warn', { max: 40, min: 1 }],
      camelcase: 'off',
      'no-shadow-restricted-names': 'error',
      'no-magic-numbers': ['warn', { ignoreArrayIndexes: true, ignore: [-1, 0, 1, 2, 3, 4, 5, 8] }],
      'multiline-comment-style': ['error', 'separate-lines'],
      'line-comment-position': ['warn', { position: 'above' }],
      'lines-around-comment': ['error', { beforeBlockComment: true, beforeLineComment: false, allowBlockStart: true }],
      'spaced-comment': ['error', 'always'],
      'no-warning-comments': ['off', { terms: ['TODO', 'FIXME', 'DTS'], location: 'anywhere' }],
      indent: ['warn', 2, { SwitchCase: 1 }],
      'max-len': ['warn', { code: 120, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true }],
      'brace-style': 'error',
      'keyword-spacing': ['error', { before: true }],
      'space-before-function-paren': ['off', 'always'],
      'no-multi-spaces': 'error',
      curly: 'error',
      'no-var': 'error',
      'one-var': ['error', 'never'],
      'no-multi-assign': 'warn',
      'no-undef-init': 'error',
      'no-undef': 'error',
      'no-new-object': 'error',
      'no-param-reassign': ['warn', { props: false }],
      'prefer-rest-params': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-parens': ['error', 'always'],
      'arrow-body-style': ['error', 'as-needed'],
      'consistent-return': 'warn',
      'no-this-before-super': 'error',
      'prefer-template': 'error',
      'prefer-destructuring': ['off', { array: true, object: true }],
      'dot-notation': 'warn',
      'accessor-pairs': 'warn',
      'no-prototype-builtins': 'error',
      'guard-for-in': 'warn',
      'no-nested-ternary': 'warn',
      'default-case': 'warn',
      'no-fallthrough': 'error',
      'no-case-declarations': 2,
      'no-duplicate-imports': 'warn',
      'no-floating-decimal': 'error',
      'use-isnan': 2,
      'no-unsafe-finally': 'error',
      'no-return-await': 'error',
      'no-with': 'error',
      'no-console': 'error',
      'no-alert': 'error',
      'no-debugger': 'error',
      'no-implicit-coercion': 'warn',
      'no-useless-return': 'error',
      'no-shadow': 'error',
      'function-paren-newline': ['warn', 'multiline'],
      'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
      'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 4 }],
      'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
      'padded-blocks': ['off', { classes: 'never' }],
      'no-multiple-empty-lines': ['warn', { max: 1 }],
      'object-curly-spacing': ['warn', 'always'],
      'array-bracket-spacing': ['warn', 'never'],
      'comma-dangle': ['warn', 'always-multiline'],
      semi: ['warn', 'always'],
      'comma-spacing': ['warn', { before: false, after: true }],
      'max-lines': ['warn', 2000],
      'max-lines-per-function': ['warn', { max: 100 }],
      complexity: ['warn', 30],
      'max-depth': ['warn', 5],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['warn', 5],
      'func-style': ['warn', 'expression', { allowArrowFunctions: true }],
      eqeqeq: 'warn',
      'no-unexpected-multiline': 'warn',
      'no-negated-condition': 'warn',
      'no-mixed-operators': ['warn', {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: true,
      }],
      'no-implicit-globals': 'warn',
      'no-throw-literal': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'no-continue': 'warn',
      'vars-on-top': 'warn',
      strict: ['warn', 'function'],
      'no-new': 'error',
      'no-useless-escape': 'warn',
      'prefer-const': 'off',
      'no-unused-vars': ['warn', { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
      'no-tabs': 'error',
      'no-empty-function': 'warn',
      'no-duplicate-case': 2,
      'no-mixed-spaces-and-tabs': ['error'],
      'eol-last': 'error',
      'object-curly-newline': ['warn', {
        ObjectExpression: { multiline: true, minProperties: 4 },
        ObjectPattern: { multiline: true, minProperties: 4 },
        ImportDeclaration: { multiline: true, minProperties: 4 },
        ExportDeclaration: { multiline: true, minProperties: 4 },
      }],
      'quote-props': ['error', 'as-needed'],
      'key-spacing': ['error'],
      'space-before-blocks': ['error'],
      'semi-spacing': ['error', { before: false, after: true }],
      'arrow-spacing': ['error'],
      'space-in-parens': ['error', 'never'],
      'sort-imports': ['off', {
        ignoreCase: false,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
        allowSeparatedGroups: false,
      }],
    },
  },

  // 4. 测试文件覆盖配置（放宽部分规则）
  {
    files: ['**/*.test.ts', '**/*.spec.ts', '**/*.test.js', '**/*.spec.js'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-magic-numbers': 'off',
      'max-lines-per-function': 'off',
      'max-lines': 'off',
      'no-console': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': 'off',
    },
  },

  // 5. 类型定义文件覆盖配置
  {
    files: ['**/*.d.ts', '**/types/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': 'off',
      'no-magic-numbers': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-warning-comments': 'off',
    },
  },

  // 6. CameraControls — camera-controls 库的单文件类移植，超出 max-lines 限制
  {
    files: ['src/camera/CameraControls.ts'],
    rules: {
      'max-lines': 'off',
    },
  },

  // 7. 配置文件覆盖
  {
    files: ['*.config.js', '*.config.ts', '*.config.mjs', '.*rc.js'],
    rules: {
      'no-magic-numbers': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'no-console': 'off',
      '@typescript-eslint/naming-convention': 'off',
    },
  },

  // 8. 忽略文件配置
  globalIgnores([
    '**/*.d.ts',
    'dist/',
    'build/',
    'coverage/',
    'node_modules/',
    '.git/',
    '*.min.js',
    '*.min.ts',
    '**/__tests__/fixtures/**',
    '**/__mocks__/**',
    'docs/',
    'eslint.config.mjs',
    'vite.config.ts',
    '*.json'
  ]),
]);
